#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Setup /etc/hosts and SSHD configuration on machines
Generates and deploys /etc/hosts with machine entries
Configures SSHD for password authentication
Sets root password
"""

import sys
import os
import subprocess
from pathlib import Path
from typing import Dict, Any, List, Optional

# Add core modules to path
sys.path.insert(0, str(Path(__file__).parent.parent / "core"))

from core.ssh_client import SSHClient
from core.logger import setup_logger
from core import modify_config_file


def generate_hosts_content(machines: Dict[str, Dict[str, Any]]) -> str:
    """
    Generate /etc/hosts content from machines information.
    
    Args:
        machines: Dictionary of machine configurations
        
    Returns:
        String containing /etc/hosts content
    """
    lines = [
        "# /etc/hosts - Generated by automation",
        "# Standard localhost entries",
        "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4",
        "::1         localhost localhost.localdomain localhost6 localhost6.localdomain6",
        "",
        "# Machine entries from deployment",
    ]
    
    for machine_name, machine_info in sorted(machines.items()):
        private_ip = machine_info.get('private_ip', '')
        if not private_ip:
            continue
        
        # Add entry with short name and demo.guardium domain
        short_name = machine_name
        fqdn = f"{machine_name}.demo.guardium"
        
        lines.append(f"{private_ip:<15} {fqdn} {short_name}")
    
    lines.append("")  # Empty line at end
    return "\n".join(lines)


def update_hosts_file_local(hosts_content: str, logger) -> bool:
    """
    Update /etc/hosts file on local machine.
    
    Args:
        hosts_content: Content to write to /etc/hosts
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    try:
        # Backup existing /etc/hosts
        logger.info("Backing up existing /etc/hosts")
        result = subprocess.run(
            ["cp", "/etc/hosts", "/etc/hosts.backup"],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            logger.warning(f"Could not backup /etc/hosts: {result.stderr}")
        
        # Write new /etc/hosts content
        logger.info("Writing new /etc/hosts content")
        
        # Create temporary file with new content
        temp_file = "/tmp/hosts.new"
        with open(temp_file, 'w') as f:
            f.write(hosts_content)
        
        # Move temporary file to /etc/hosts
        logger.info("Installing new /etc/hosts")
        result = subprocess.run(
            ["mv", temp_file, "/etc/hosts"],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            logger.error(f"Failed to install /etc/hosts: {result.stderr}")
            return False
        
        # Set proper permissions
        result = subprocess.run(
            ["chmod", "644", "/etc/hosts"],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            logger.warning(f"Could not set permissions on /etc/hosts: {result.stderr}")
        
        logger.info("Successfully updated /etc/hosts")
        return True
        
    except Exception as e:
        logger.error(f"Error updating /etc/hosts: {str(e)}")
        return False


def update_hosts_file_remote(ssh_client: SSHClient, hosts_content: str, logger) -> bool:
    """
    Update /etc/hosts file on remote machine via SSH using sudo.
    """
    try:
        logger.info("Backing up existing /etc/hosts")
        backup_result = ssh_client.execute_command("sudo cp /etc/hosts /etc/hosts.backup", print_output=False)
        if backup_result['rc'] != 0:
            logger.warning(f"Could not backup /etc/hosts: {backup_result['stderr']}")
        
        logger.info("Writing new /etc/hosts content")
        temp_file = "/tmp/hosts.new"
        write_cmd = f"cat > {temp_file} << 'EOF'\n{hosts_content}\nEOF"
        
        result = ssh_client.execute_command(write_cmd, print_output=False)
        if result['rc'] != 0:
            logger.error(f"Failed to write temporary hosts file: {result['stderr']}")
            return False
        
        logger.info("Installing new /etc/hosts")
        result = ssh_client.execute_command(f"sudo mv {temp_file} /etc/hosts", print_output=False)
        if result['rc'] != 0:
            logger.error(f"Failed to install /etc/hosts: {result['stderr']}")
            return False
        
        result = ssh_client.execute_command("sudo chmod 644 /etc/hosts", print_output=False)
        if result['rc'] != 0:
            logger.warning(f"Could not set permissions on /etc/hosts: {result['stderr']}")
        
        logger.info("Successfully updated /etc/hosts")
        return True
        
    except Exception as e:
        logger.error(f"Error updating /etc/hosts: {str(e)}")
        return False


def configure_sshd_local(logger) -> bool:
    """
    Configure SSHD on local machine.
    Changes:
    - PasswordAuthentication yes
    - PermitRootLogin yes
    - LoginGraceTime 0
    
    Args:
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    try:
        sshd_config = "/etc/ssh/sshd_config"
        
        logger.info("Modifying SSHD configuration")
        
        # Replace or add PasswordAuthentication setting
        if not modify_config_file(
            path=sshd_config,
            content='PasswordAuthentication yes\n',
            mode='replace',
            pattern=r'^#*\s*PasswordAuthentication',
            backup=True,
            logger=logger
        ):
            # If pattern not found, append it
            modify_config_file(
                path=sshd_config,
                content='\n# Added by automation\nPasswordAuthentication yes\n',
                mode='append',
                backup=False,
                logger=logger
            )
        
        # Replace or add PermitRootLogin setting
        if not modify_config_file(
            path=sshd_config,
            content='PermitRootLogin yes\n',
            mode='replace',
            pattern=r'^#*\s*PermitRootLogin',
            backup=False,
            logger=logger
        ):
            modify_config_file(
                path=sshd_config,
                content='PermitRootLogin yes\n',
                mode='append',
                backup=False,
                logger=logger
            )
        
        # Replace or add LoginGraceTime setting
        if not modify_config_file(
            path=sshd_config,
            content='LoginGraceTime 0\n',
            mode='replace',
            pattern=r'^#*\s*LoginGraceTime',
            backup=False,
            logger=logger
        ):
            modify_config_file(
                path=sshd_config,
                content='LoginGraceTime 0\n',
                mode='append',
                backup=False,
                logger=logger
            )
        
        # Set proper permissions
        result = subprocess.run(
            ["chmod", "600", sshd_config],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            logger.warning(f"Could not set permissions on sshd_config: {result.stderr}")
        
        # Remove cloud-init override config if exists
        cloud_init_config = "/etc/ssh/sshd_config.d/50-cloud-init.conf"
        logger.info(f"Removing {cloud_init_config} if exists")
        result = subprocess.run(
            ["rm", "-f", cloud_init_config],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            logger.warning(f"Could not remove {cloud_init_config}: {result.stderr}")
        
        # Restart SSHD
        logger.info("Restarting SSHD service")
        result = subprocess.run(
            ["systemctl", "restart", "sshd"],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            logger.error(f"Failed to restart SSHD: {result.stderr}")
            return False
        
        logger.info("Successfully configured SSHD")
        return True
        
    except Exception as e:
        logger.error(f"Error configuring SSHD: {str(e)}")
        return False


def set_root_password_local(password: str, logger) -> bool:
    """
    Set root password on local machine.
    
    Args:
        password: New root password
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    try:
        logger.info("Setting root password on local machine")
        
        # Use chpasswd to set password
        # Format: username:password
        process = subprocess.Popen(
            ["chpasswd"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        
        stdout, stderr = process.communicate(input=f"root:{password}\n")
        
        if process.returncode != 0:
            logger.error(f"Failed to set root password: {stderr}")
            return False
        
        logger.info("Successfully set root password")
        return True
        
    except Exception as e:
        logger.error(f"Error setting root password: {str(e)}")
        return False


def set_root_password_remote(ssh_client: SSHClient, password: str, logger) -> bool:
    """
    Set root password on remote machine via SSH.
    
    Args:
        ssh_client: SSH client instance
        password: New root password
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    try:
        logger.info("Setting root password on remote machine")
        
        # Use chpasswd with sudo
        # We need to pass the password securely through stdin
        cmd = f"echo 'root:{password}' | sudo chpasswd"
        
        result = ssh_client.execute_command(cmd, print_output=False)
        if result['rc'] != 0:
            logger.error(f"Failed to set root password: {result['stderr']}")
            return False
        
        logger.info("Successfully set root password")
        return True
        
    except Exception as e:
        logger.error(f"Error setting root password: {str(e)}")
        return False


def set_hostname_local(hostname: str, logger) -> bool:
    """
    Set hostname on local machine using hostnamectl.
    
    Args:
        hostname: New hostname to set
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    try:
        logger.info(f"Setting hostname to: {hostname}")
        
        result = subprocess.run(
            ["hostnamectl", "set-hostname", hostname],
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            logger.error(f"Failed to set hostname: {result.stderr}")
            return False
        
        logger.info(f"Successfully set hostname to {hostname}")
        return True
        
    except Exception as e:
        logger.error(f"Error setting hostname: {str(e)}")
        return False


def set_hostname_remote(ssh_client: SSHClient, hostname: str, logger) -> bool:
    """
    Set hostname on remote machine via SSH using hostnamectl.
    
    Args:
        ssh_client: SSH client instance
        hostname: New hostname to set
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    try:
        logger.info(f"Setting hostname to: {hostname}")
        
        cmd = f"sudo hostnamectl set-hostname {hostname}"
        
        result = ssh_client.execute_command(cmd, print_output=False)
        if result['rc'] != 0:
            logger.error(f"Failed to set hostname: {result['stderr']}")
            return False
        
        logger.info(f"Successfully set hostname to {hostname}")
        return True
        
    except Exception as e:
        logger.error(f"Error setting hostname: {str(e)}")
        return False


def set_timezone_local(timezone: str, logger) -> bool:
    """
    Set timezone on local machine using timedatectl.
    
    Args:
        timezone: Timezone to set (e.g., 'Europe/Warsaw')
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    try:
        logger.info(f"Setting timezone to: {timezone}")
        
        result = subprocess.run(
            ["timedatectl", "set-timezone", timezone],
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            logger.error(f"Failed to set timezone: {result.stderr}")
            return False
        
        logger.info(f"Successfully set timezone to {timezone}")
        return True
        
    except Exception as e:
        logger.error(f"Error setting timezone: {str(e)}")
        return False


def set_timezone_remote(ssh_client: SSHClient, timezone: str, logger) -> bool:
    """
    Set timezone on remote machine via SSH using timedatectl.
    
    Args:
        ssh_client: SSH client instance
        timezone: Timezone to set (e.g., 'Europe/Warsaw')
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    try:
        logger.info(f"Setting timezone to: {timezone}")
        
        cmd = f"sudo timedatectl set-timezone {timezone}"
        
        result = ssh_client.execute_command(cmd, print_output=False)
        if result['rc'] != 0:
            logger.error(f"Failed to set timezone: {result['stderr']}")
            return False
        
        logger.info(f"Successfully set timezone to {timezone}")
        return True
        
    except Exception as e:
        logger.error(f"Error setting timezone: {str(e)}")
        return False


def configure_sshd_remote(ssh_client: SSHClient, logger) -> bool:
    """
    Configure SSHD on remote machine via SSH using sudo.
    Changes:
    - PasswordAuthentication yes
    - PermitRootLogin yes
    - LoginGraceTime 0
    
    Args:
        ssh_client: SSH client instance
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    try:
        sshd_config = "/etc/ssh/sshd_config"
        
        logger.info("Backing up existing sshd_config")
        backup_result = ssh_client.execute_command(f"sudo cp {sshd_config} {sshd_config}.backup", print_output=False)
        if backup_result['rc'] != 0:
            logger.warning(f"Could not backup sshd_config: {backup_result['stderr']}")
        
        logger.info("Modifying SSHD configuration")
        
        # Use sed to modify the configuration in place
        commands = [
            # Change or add PasswordAuthentication
            f"sudo sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' {sshd_config}",
            # Change or add PermitRootLogin
            f"sudo sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' {sshd_config}",
            # Change or add LoginGraceTime
            f"sudo sed -i 's/^#*LoginGraceTime.*/LoginGraceTime 0/' {sshd_config}",
        ]
        
        for cmd in commands:
            result = ssh_client.execute_command(cmd, print_output=False)
            if result['rc'] != 0:
                logger.warning(f"Command failed: {cmd}\nError: {result['stderr']}")
        
        # Verify settings exist, if not append them
        verify_and_add = """
if ! grep -q '^PasswordAuthentication' /etc/ssh/sshd_config; then
    echo 'PasswordAuthentication yes' | sudo tee -a /etc/ssh/sshd_config
fi
if ! grep -q '^PermitRootLogin' /etc/ssh/sshd_config; then
    echo 'PermitRootLogin yes' | sudo tee -a /etc/ssh/sshd_config
fi
if ! grep -q '^LoginGraceTime' /etc/ssh/sshd_config; then
    echo 'LoginGraceTime 0' | sudo tee -a /etc/ssh/sshd_config
fi
"""
        result = ssh_client.execute_command(verify_and_add, print_output=False)
        if result['rc'] != 0:
            logger.warning(f"Could not verify/add settings: {result['stderr']}")
        
        # Set proper permissions
        result = ssh_client.execute_command(f"sudo chmod 600 {sshd_config}", print_output=False)
        if result['rc'] != 0:
            logger.warning(f"Could not set permissions on sshd_config: {result['stderr']}")
        
        # Remove cloud-init override config if exists
        cloud_init_config = "/etc/ssh/sshd_config.d/50-cloud-init.conf"
        logger.info(f"Removing {cloud_init_config} if exists")
        result = ssh_client.execute_command(f"sudo rm -f {cloud_init_config}", print_output=False)
        if result['rc'] != 0:
            logger.warning(f"Could not remove {cloud_init_config}: {result['stderr']}")
        
        # Restart SSHD
        logger.info("Restarting SSHD service")
        result = ssh_client.execute_command("sudo systemctl restart sshd", print_output=False)
        if result['rc'] != 0:
            logger.error(f"Failed to restart SSHD: {result['stderr']}")
            return False
        
        logger.info("Successfully configured SSHD")
        return True
        
    except Exception as e:
        logger.error(f"Error configuring SSHD: {str(e)}")
        return False


def setup_hosts_locally(all_machines: Dict[str, Dict[str, Any]], logger,
                        machine_name: str = "raptor",
                        configure_sshd: bool = True,
                        root_password: Optional[str] = None,
                        timezone: Optional[str] = None,
                        verbose: bool = True) -> bool:
    """
    Setup /etc/hosts, hostname, timezone, SSHD, and root password on local machine (raptor).
    
    Args:
        all_machines: All machines in the deployment
        logger: Logger instance
        machine_name: Name of the local machine (default: raptor)
        configure_sshd: Whether to configure SSHD (default: True)
        root_password: Root password to set (optional)
        timezone: Timezone to set (optional)
        verbose: Enable verbose logging (default: True)
        
    Returns:
        True if successful, False otherwise
    """
    logger.info(f"Setting up local machine ({machine_name})")
    
    # Set hostname
    hostname = f"{machine_name}.guardium.demo"
    logger.info(f"Setting hostname to {hostname}")
    hostname_success = set_hostname_local(hostname, logger)
    if not hostname_success:
        logger.error("Failed to set hostname")
        return False
    
    # Set timezone if provided
    if timezone:
        logger.info(f"Setting timezone to {timezone}")
        timezone_success = set_timezone_local(timezone, logger)
        if not timezone_success:
            logger.error("Failed to set timezone")
            return False
    
    # Setup /etc/hosts
    logger.info("Configuring /etc/hosts")
    hosts_content = generate_hosts_content(all_machines)
    logger.debug(f"Generated /etc/hosts content:\n{hosts_content}")
    
    hosts_success = update_hosts_file_local(hosts_content, logger)
    if not hosts_success:
        logger.error("Failed to update /etc/hosts")
        return False
    
    # Configure SSHD if requested
    if configure_sshd:
        logger.info("Configuring SSHD")
        sshd_success = configure_sshd_local(logger)
        if not sshd_success:
            logger.error("Failed to configure SSHD")
            return False
    
    # Set root password if provided
    if root_password:
        logger.info("Setting root password")
        pwd_success = set_root_password_local(root_password, logger)
        if not pwd_success:
            logger.error("Failed to set root password")
            return False
    
    logger.info("Local machine setup completed successfully")
    return True


def setup_hosts_on_remote_machine(machine_name: str, machine_info: Dict[str, Any],
                                  all_machines: Dict[str, Dict[str, Any]],
                                  credentials: Dict[str, Any], logger,
                                  use_private_ip: bool = True,
                                  ssh_port: int = 2223,
                                  configure_sshd: bool = True,
                                  root_password: Optional[str] = None,
                                  timezone: Optional[str] = None,
                                  verbose: bool = True) -> bool:
    """
    Setup hostname, timezone, /etc/hosts, SSHD, and root password on a remote machine via SSH.
    
    Args:
        machine_name: Name of the machine
        machine_info: Machine configuration
        all_machines: All machines in the deployment
        credentials: SSH credentials
        logger: Logger instance
        use_private_ip: Use private IP instead of public (default: True)
        ssh_port: SSH port (default: 2223)
        configure_sshd: Whether to configure SSHD (default: True)
        root_password: Root password to set (optional)
        timezone: Timezone to set (optional)
        
    Returns:
        True if successful, False otherwise
    """
    if use_private_ip:
        host = machine_info.get('private_ip')
        if not host:
            logger.warning(f"No private IP for {machine_name}, using public IP")
            host = machine_info.get('host')
    else:
        host = machine_info.get('host')
    
    if not host:
        logger.error(f"No IP address for {machine_name}")
        return False
    
    logger.info(f"Setting up remote machine {machine_name} ({host}:{ssh_port})")
    
    hosts_content = generate_hosts_content(all_machines)
    username = credentials.get('username', 'root')
    
    try:
        with SSHClient(host=host, username=username, port=ssh_port) as ssh:
            logger.info(f"Connected to {machine_name}")
            
            # Set hostname
            hostname = f"{machine_name}.guardium.demo"
            logger.info(f"Setting hostname to {hostname}")
            hostname_success = set_hostname_remote(ssh, hostname, logger)
            if not hostname_success:
                logger.error("Failed to set hostname")
                return False
            
            # Set timezone if provided
            if timezone:
                logger.info(f"Setting timezone to {timezone}")
                timezone_success = set_timezone_remote(ssh, timezone, logger)
                if not timezone_success:
                    logger.error("Failed to set timezone")
                    return False
            
            # Setup /etc/hosts
            logger.info("Configuring /etc/hosts")
            hosts_success = update_hosts_file_remote(ssh, hosts_content, logger)
            if not hosts_success:
                logger.error("Failed to update /etc/hosts")
                return False
            
            # Configure SSHD if requested
            if configure_sshd:
                logger.info("Configuring SSHD")
                sshd_success = configure_sshd_remote(ssh, logger)
                if not sshd_success:
                    logger.error("Failed to configure SSHD")
                    return False
            
            # Set root password if provided
            if root_password:
                logger.info("Setting root password")
                pwd_success = set_root_password_remote(ssh, root_password, logger)
                if not pwd_success:
                    logger.error("Failed to set root password")
                    return False
            
            logger.info(f"Remote machine {machine_name} setup completed successfully")
            return True
            
    except Exception as e:
        logger.error(f"Failed to setup {machine_name}: {str(e)}")
        return False

def setup_hosts_task(config, logger, verbose: bool = True) -> bool:
    """
    Wrapper function for group-based execution.
    Sets up hostname, timezone, /etc/hosts, SSHD, and root password on all machines.
    
    Args:
        config: ConfigLoader instance
        logger: Logger instance
        verbose: Enable verbose logging
        
    Returns:
        True if successful, False otherwise
    """
    machines = config.get_machines()
    
    # Get credentials from custom_variables (new JSON format)
    credentials = {
        'username': config.get_custom_variable('username', 'root'),
        'password': config.get_custom_variable('password'),
        'ssh_key': config.get_custom_variable('ssh_private_key')
    }
    
    root_password = config.get_custom_variable('pwd')
    timezone = config.get_custom_variable('timezone')
    
    # Setup local machine (raptor)
    if verbose:
        logger.info("Setting up local machine (raptor)")
    
    success = setup_hosts_locally(
        all_machines=machines,
        logger=logger,
        machine_name="raptor",
        configure_sshd=True,
        root_password=root_password,
        timezone=timezone,
        verbose=verbose
    )
    
    if not success:
        logger.error("Failed to setup local machine")
        return False
    
    # Setup remote machines
    remote_machines = config.get('tasks', {}).get('remote_machines', [])
    
    for machine_name in remote_machines:
        machine_info = config.get_machine(machine_name)
        if not machine_info:
            logger.warning(f"Machine {machine_name} not found in configuration")
            continue
        
        if verbose:
            logger.info(f"Setting up remote machine: {machine_name}")
        
        success = setup_hosts_on_remote_machine(
            machine_name=machine_name,
            machine_info=machine_info,
            all_machines=machines,
            credentials=credentials,
            logger=logger,
            use_private_ip=True,
            configure_sshd=True,
            root_password=root_password,
            timezone=timezone,
            verbose=verbose
        )
        
        if not success:
            logger.error(f"Failed to setup remote machine: {machine_name}")
            return False
    
    return True



# Made with Bob