#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Setup /etc/hosts file on machines
Generates and deploys /etc/hosts with machine entries
"""

import sys
import os
import subprocess
from pathlib import Path
from typing import Dict, Any, List

# Add core modules to path
sys.path.insert(0, str(Path(__file__).parent.parent / "core"))

from core.ssh_client import SSHClient
from core.logger import setup_logger


def generate_hosts_content(machines: Dict[str, Dict[str, Any]]) -> str:
    """
    Generate /etc/hosts content from machines information.
    
    Args:
        machines: Dictionary of machine configurations
        
    Returns:
        String containing /etc/hosts content
    """
    lines = [
        "# /etc/hosts - Generated by automation",
        "# Standard localhost entries",
        "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4",
        "::1         localhost localhost.localdomain localhost6 localhost6.localdomain6",
        "",
        "# Machine entries from deployment",
    ]
    
    for machine_name, machine_info in sorted(machines.items()):
        private_ip = machine_info.get('private_ip', '')
        if not private_ip:
            continue
        
        # Add entry with short name and demo.guardium domain
        short_name = machine_name
        fqdn = f"{machine_name}.demo.guardium"
        
        lines.append(f"{private_ip:<15} {fqdn} {short_name}")
    
    lines.append("")  # Empty line at end
    return "\n".join(lines)


def update_hosts_file_local(hosts_content: str, logger) -> bool:
    """
    Update /etc/hosts file on local machine.
    
    Args:
        hosts_content: Content to write to /etc/hosts
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    try:
        # Backup existing /etc/hosts
        logger.info("Backing up existing /etc/hosts")
        result = subprocess.run(
            ["cp", "/etc/hosts", "/etc/hosts.backup"],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            logger.warning(f"Could not backup /etc/hosts: {result.stderr}")
        
        # Write new /etc/hosts content
        logger.info("Writing new /etc/hosts content")
        
        # Create temporary file with new content
        temp_file = "/tmp/hosts.new"
        with open(temp_file, 'w') as f:
            f.write(hosts_content)
        
        # Move temporary file to /etc/hosts
        logger.info("Installing new /etc/hosts")
        result = subprocess.run(
            ["mv", temp_file, "/etc/hosts"],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            logger.error(f"Failed to install /etc/hosts: {result.stderr}")
            return False
        
        # Set proper permissions
        result = subprocess.run(
            ["chmod", "644", "/etc/hosts"],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            logger.warning(f"Could not set permissions on /etc/hosts: {result.stderr}")
        
        logger.info("Successfully updated /etc/hosts")
        return True
        
    except Exception as e:
        logger.error(f"Error updating /etc/hosts: {str(e)}")
        return False


def update_hosts_file_remote(ssh_client: SSHClient, hosts_content: str, logger) -> bool:
    """
    Update /etc/hosts file on remote machine via SSH using sudo.
    """
    try:
        logger.info("Backing up existing /etc/hosts")
        backup_result = ssh_client.execute_command("sudo cp /etc/hosts /etc/hosts.backup", print_output=False)
        if backup_result['rc'] != 0:
            logger.warning(f"Could not backup /etc/hosts: {backup_result['stderr']}")
        
        logger.info("Writing new /etc/hosts content")
        temp_file = "/tmp/hosts.new"
        write_cmd = f"cat > {temp_file} << 'EOF'\n{hosts_content}\nEOF"
        
        result = ssh_client.execute_command(write_cmd, print_output=False)
        if result['rc'] != 0:
            logger.error(f"Failed to write temporary hosts file: {result['stderr']}")
            return False
        
        logger.info("Installing new /etc/hosts")
        result = ssh_client.execute_command(f"sudo mv {temp_file} /etc/hosts", print_output=False)
        if result['rc'] != 0:
            logger.error(f"Failed to install /etc/hosts: {result['stderr']}")
            return False
        
        result = ssh_client.execute_command("sudo chmod 644 /etc/hosts", print_output=False)
        if result['rc'] != 0:
            logger.warning(f"Could not set permissions on /etc/hosts: {result['stderr']}")
        
        logger.info("Successfully updated /etc/hosts")
        return True
        
    except Exception as e:
        logger.error(f"Error updating /etc/hosts: {str(e)}")
        return False


def setup_hosts_locally(all_machines: Dict[str, Dict[str, Any]], logger) -> bool:
    """
    Setup /etc/hosts on local machine (raptor).
    
    Args:
        all_machines: All machines in the deployment
        logger: Logger instance
        
    Returns:
        True if successful, False otherwise
    """
    logger.info("Setting up /etc/hosts on local machine (raptor)")
    
    # Generate hosts content
    hosts_content = generate_hosts_content(all_machines)
    logger.debug(f"Generated /etc/hosts content:\n{hosts_content}")
    
    # Update local /etc/hosts
    return update_hosts_file_local(hosts_content, logger)


def setup_hosts_on_remote_machine(machine_name: str, machine_info: Dict[str, Any],
                                  all_machines: Dict[str, Dict[str, Any]],
                                  credentials: Dict[str, Any], logger,
                                  use_private_ip: bool = True,
                                  ssh_port: int = 2223) -> bool:
    """
    Setup /etc/hosts on a remote machine via SSH.
    """
    if use_private_ip:
        host = machine_info.get('private_ip')
        if not host:
            logger.warning(f"No private IP for {machine_name}, using public IP")
            host = machine_info.get('host')
    else:
        host = machine_info.get('host')
    
    if not host:
        logger.error(f"No IP address for {machine_name}")
        return False
    
    logger.info(f"Setting up /etc/hosts on {machine_name} ({host}:{ssh_port})")
    
    hosts_content = generate_hosts_content(all_machines)
    username = credentials.get('username', 'root')
    
    try:
        with SSHClient(host=host, username=username, port=ssh_port) as ssh:
            logger.info(f"Connected to {machine_name}")
            return update_hosts_file_remote(ssh, hosts_content, logger)
            
    except Exception as e:
        logger.error(f"Failed to setup hosts on {machine_name}: {str(e)}")
        return False


# Made with Bob